/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.RevenueDataPoint;
import BUS.RevenueStatisticsBUS;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

import javax.swing.*;
import java.awt.*;
import java.time.LocalDate;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.time.temporal.TemporalAdjusters;
import java.util.List;

/**
 *
 * @author pc
 */
public class RevenueProductStatisticsGUI extends javax.swing.JPanel {

    /**
     * Creates new form RevenueProductStatisticsGUI
     */
    public RevenueProductStatisticsGUI() {
        initComponents();
    }

    private void drawChart(List<RevenueDataPoint> dataPoints, LocalDate startDate, LocalDate endDate, String timeUnit) {

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (RevenueDataPoint dataPoint : dataPoints) {
            dataset.addValue(dataPoint.getRevenue(), "Revenue", dataPoint.getLabel());
        }

        JFreeChart chart = ChartFactory.createBarChart(
                "Revenue " + timeUnit + " (" + startDate + " - " + endDate + ")",
                timeUnit,
                "Revenue (VND)",
                dataset, // data
                PlotOrientation.VERTICAL,
                false,
                true,
                false
        );

        CategoryPlot plot = chart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.BLACK);

        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setSize(jPanel5.getWidth(), jPanel5.getHeight());
        chartPanel.setPreferredSize(new Dimension(jPanel5.getWidth(), jPanel5.getHeight()));
        chartPanel.setVisible(true);
        jPanel5.removeAll();
        jPanel5.add(chartPanel);
        jPanel5.revalidate();
        jPanel5.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnStatisticByYear = new javax.swing.JButton();
        txtStartYear = new javax.swing.JTextField();
        txtEndYear = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtStartMonth = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEndMonth = new javax.swing.JTextField();
        btnStatisticByMonth = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtStartDay = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEndDay = new javax.swing.JTextField();
        btnStatisticByDay = new javax.swing.JButton();
        txtTotalOrders = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtTotalRevenue = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("REVENUE STATISTICS");
        jPanel1.add(jLabel2);

        jPanel3.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBackground(new java.awt.Color(255, 204, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(500, 380));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1014, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(500, 170));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("From:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("To:");

        btnStatisticByYear.setBackground(new java.awt.Color(51, 153, 255));
        btnStatisticByYear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnStatisticByYear.setText("Statistics by year");
        btnStatisticByYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatisticByYearActionPerformed(evt);
            }
        });

        txtStartYear.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtStartYear.setForeground(new java.awt.Color(102, 102, 102));
        txtStartYear.setText("yyyy");
        txtStartYear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtStartYearFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtStartYearFocusLost(evt);
            }
        });

        txtEndYear.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtEndYear.setForeground(new java.awt.Color(102, 102, 102));
        txtEndYear.setText("yyyy");
        txtEndYear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEndYearFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEndYearFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("From:");

        txtStartMonth.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtStartMonth.setForeground(new java.awt.Color(102, 102, 102));
        txtStartMonth.setText("mm/yyyy");
        txtStartMonth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtStartMonthFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtStartMonthFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("To:");

        txtEndMonth.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtEndMonth.setForeground(new java.awt.Color(102, 102, 102));
        txtEndMonth.setText("mm/yyyy");
        txtEndMonth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEndMonthFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEndMonthFocusLost(evt);
            }
        });

        btnStatisticByMonth.setBackground(new java.awt.Color(51, 153, 255));
        btnStatisticByMonth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnStatisticByMonth.setText("Statistics by month");
        btnStatisticByMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatisticByMonthActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("From:");

        txtStartDay.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtStartDay.setForeground(new java.awt.Color(102, 102, 102));
        txtStartDay.setText("dd/mm/yyyy");
        txtStartDay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtStartDayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtStartDayFocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("To:");

        txtEndDay.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtEndDay.setForeground(new java.awt.Color(102, 102, 102));
        txtEndDay.setText("dd/mm/yyyy");
        txtEndDay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEndDayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEndDayFocusLost(evt);
            }
        });

        btnStatisticByDay.setBackground(new java.awt.Color(51, 153, 255));
        btnStatisticByDay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnStatisticByDay.setText("Statistics by day");
        btnStatisticByDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatisticByDayActionPerformed(evt);
            }
        });

        txtTotalOrders.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTotalOrders.setForeground(new java.awt.Color(102, 102, 102));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Total revenue:");

        txtTotalRevenue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTotalRevenue.setForeground(new java.awt.Color(102, 102, 102));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Total orders:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addGap(12, 12, 12)
                        .addComponent(txtTotalRevenue))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStartDay, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStartMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEndMonth)
                                .addComponent(txtEndDay, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtEndYear, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnStatisticByYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStatisticByMonth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStatisticByDay, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(396, 396, 396))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtStartYear, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStatisticByYear)
                    .addComponent(txtEndYear, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtStartMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStatisticByMonth)
                    .addComponent(txtEndMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txtStartDay, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStatisticByDay)
                    .addComponent(txtEndDay, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtTotalOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtTotalRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStatisticByYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatisticByYearActionPerformed
        if (txtStartYear.getText().isEmpty() || txtEndYear.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Do not leave the field blank !",
                "Error message", JOptionPane.ERROR_MESSAGE);
        }

        int startYear = Integer.parseInt(txtStartYear.getText());
        int endYear = Integer.parseInt(txtEndYear.getText());

        RevenueStatisticsBUS revenueStatisticsBUS = new RevenueStatisticsBUS();
        LocalDate startDate = LocalDate.of(startYear, 1, 1);
        LocalDate endDate = LocalDate.of(endYear, 12, 31);
        List<RevenueDataPoint> dataPoints = revenueStatisticsBUS.getYearlyRevenue(startDate, endDate);

        double totalRevenue = 0;
        for (RevenueDataPoint dataPoint : dataPoints) {
            totalRevenue += dataPoint.getRevenue();
        }

        txtTotalRevenue.setText("%.2f".formatted(totalRevenue));
        txtTotalOrders.setText(Integer.toString(dataPoints.size()));

        drawChart(dataPoints, startDate, endDate, "Year");
    }//GEN-LAST:event_btnStatisticByYearActionPerformed

    private void txtStartYearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStartYearFocusGained
        if (txtStartYear.getText().equals("yyyy")) {
            txtStartYear.setText("");
        }
    }//GEN-LAST:event_txtStartYearFocusGained

    private void txtStartYearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStartYearFocusLost
        if (txtStartYear.getText().isEmpty()) {
            txtStartYear.setText("yyyy");
        }
    }//GEN-LAST:event_txtStartYearFocusLost

    private void txtEndYearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEndYearFocusGained
        if (txtEndYear.getText().equals("yyyy")) {
            txtEndYear.setText("");
        }
    }//GEN-LAST:event_txtEndYearFocusGained

    private void txtEndYearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEndYearFocusLost
        if (txtEndYear.getText().isEmpty()) {
            txtEndYear.setText("yyyy");
        }
    }//GEN-LAST:event_txtEndYearFocusLost

    private void txtStartMonthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStartMonthFocusGained
        if (txtStartMonth.getText().equals("mm/yyyy")) {
            txtStartMonth.setText("");
        }
    }//GEN-LAST:event_txtStartMonthFocusGained

    private void txtStartMonthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStartMonthFocusLost
        if (txtStartMonth.getText().isEmpty()) {
            txtStartMonth.setText("mm/yyyy");
        }
    }//GEN-LAST:event_txtStartMonthFocusLost

    private void txtEndMonthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEndMonthFocusGained
        if (txtEndMonth.getText().equals("mm/yyyy")) {
            txtEndMonth.setText("");
        }
    }//GEN-LAST:event_txtEndMonthFocusGained

    private void txtEndMonthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEndMonthFocusLost
        if (txtEndMonth.getText().isEmpty()) {
            txtEndMonth.setText("mm/yyyy");
        }
    }//GEN-LAST:event_txtEndMonthFocusLost

    private void btnStatisticByMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatisticByMonthActionPerformed
        if (txtStartMonth.getText().isEmpty() || txtEndMonth.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Do not leave the field blank !",
                "Error message", JOptionPane.ERROR_MESSAGE);
        }

        String start = txtStartMonth.getText();
        String end = txtEndMonth.getText();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate startDate = LocalDate.parse("01/" + start, formatter);
        LocalDate endDate = LocalDate.parse("01/" + end, formatter).with(TemporalAdjusters.lastDayOfMonth());

        RevenueStatisticsBUS revenueStatisticsBUS = new RevenueStatisticsBUS();
        List<RevenueDataPoint> dataPoints = revenueStatisticsBUS.getMonthlyRevenue(startDate, endDate);

        double totalRevenue = 0;
        for (RevenueDataPoint dataPoint : dataPoints) {
            totalRevenue += dataPoint.getRevenue();
        }

        txtTotalRevenue.setText("%.2f".formatted(totalRevenue));
        txtTotalOrders.setText(Integer.toString(dataPoints.size()));

        drawChart(dataPoints, startDate, endDate, "Month");
    }//GEN-LAST:event_btnStatisticByMonthActionPerformed

    private void txtStartDayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStartDayFocusGained
        if (txtStartDay.getText().equals("dd/mm/yyyy")) {
            txtStartDay.setText("");
        }
    }//GEN-LAST:event_txtStartDayFocusGained

    private void txtStartDayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStartDayFocusLost
        if (txtStartDay.getText().isEmpty()) {
            txtStartDay.setText("dd/mm/yyyy");
        }
    }//GEN-LAST:event_txtStartDayFocusLost

    private void txtEndDayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEndDayFocusGained
        if (txtEndDay.getText().equals("dd/mm/yyyy")) {
            txtEndDay.setText("");
        }
    }//GEN-LAST:event_txtEndDayFocusGained

    private void txtEndDayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEndDayFocusLost
        if (txtEndDay.getText().isEmpty()) {
            txtEndDay.setText("dd/mm/yyyy");
        }
    }//GEN-LAST:event_txtEndDayFocusLost

    private void btnStatisticByDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatisticByDayActionPerformed
        if (txtStartDay.getText().isEmpty() || txtEndDay.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Do not leave the field blank !",
                "Error message", JOptionPane.ERROR_MESSAGE);
        }

        String start = txtStartDay.getText();
        String end = txtEndDay.getText();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate startDate = LocalDate.parse(start, formatter);
        LocalDate endDate = LocalDate.parse(end, formatter);

        RevenueStatisticsBUS revenueStatisticsBUS = new RevenueStatisticsBUS();
        List<RevenueDataPoint> dataPoints = revenueStatisticsBUS.getDailyRevenue(startDate, endDate);

        double totalRevenue = 0;
        for (RevenueDataPoint dataPoint : dataPoints) {
            totalRevenue += dataPoint.getRevenue();
        }

        txtTotalRevenue.setText("%.2f".formatted(totalRevenue));
        txtTotalOrders.setText(Integer.toString(dataPoints.size()));

        drawChart(dataPoints, startDate, endDate, "Day");
    }//GEN-LAST:event_btnStatisticByDayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStatisticByDay;
    private javax.swing.JButton btnStatisticByMonth;
    private javax.swing.JButton btnStatisticByYear;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txtEndDay;
    private javax.swing.JTextField txtEndMonth;
    private javax.swing.JTextField txtEndYear;
    private javax.swing.JTextField txtStartDay;
    private javax.swing.JTextField txtStartMonth;
    private javax.swing.JTextField txtStartYear;
    private javax.swing.JTextField txtTotalOrders;
    private javax.swing.JTextField txtTotalRevenue;
    // End of variables declaration//GEN-END:variables
}
